/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.*;

import javax.swing.JFrame;

/**
 *
 * @author krats
 */
public class CreacionGUI<T> extends javax.swing.JFrame {

	T t;
	JFrame padre;

	/**
	 * Creates new form CreacionGUI
	 */
	public CreacionGUI() {
		initComponents();
	}

	public CreacionGUI(JFrame padre, Class<? extends T> c) {
		initComponents();
		this.padre = padre;
		try {
			t = c.newInstance();
		} catch (IllegalAccessException ex) {

		} catch (InstantiationException ex) {

		}

		if (t instanceof Equipo) {
			posicionesCB.setVisible(false);
			posicionesL.setVisible(false);
			descL.setVisible(false);
			descTF.setVisible(false);
			dorsalL.setVisible(false);
			dorsalTF.setVisible(false);
			equiposL.setVisible(false);
			equiposJugadoresList.setVisible(false);
			fechaFinDC.setVisible(false);
			fechaFinL.setVisible(false);
			fechaIniL.setVisible(false);
			fechaInicioDC.setVisible(false);
			guardarB.addActionListener((evt) -> {

			});
		}
		if (t instanceof Posicion) {
			nombreL.setVisible(false);
			nombreTF.setVisible(false);
			posicionesCB.setVisible(false);
			posicionesL.setVisible(false);
			dorsalL.setVisible(false);
			dorsalTF.setVisible(false);
			equiposL.setVisible(false);
			equiposJugadoresList.setVisible(false);
			fechaFinDC.setVisible(false);
			fechaFinL.setVisible(false);
			fechaIniL.setVisible(false);
			fechaInicioDC.setVisible(false);
			guardarB.addActionListener((evt) -> {

			});
		}
		if (t instanceof Competicion) {
			descL.setVisible(false);
			descTF.setVisible(false);
			posicionesCB.setVisible(false);
			posicionesL.setVisible(false);
			dorsalL.setVisible(false);
			dorsalTF.setVisible(false);
			guardarB.addActionListener((evt) -> {

			});
		}
		if(t instanceof Jugador){
			descL.setVisible(false);
			descTF.setVisible(false);
			fechaFinDC.setVisible(false);
			fechaFinL.setVisible(false);
			fechaIniL.setVisible(false);
			fechaInicioDC.setVisible(false);
			guardarB.addActionListener((evt) -> {

			});
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreTF = new javax.swing.JTextField();
        nombreL = new javax.swing.JLabel();
        descL = new javax.swing.JLabel();
        descTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        equiposJugadoresList = new javax.swing.JList<>();
        equiposL = new javax.swing.JLabel();
        fechaInicioDC = new com.toedter.calendar.JDateChooser();
        guardarB = new javax.swing.JButton();
        descartarB = new javax.swing.JButton();
        salirB = new javax.swing.JButton();
        fechaIniL = new javax.swing.JLabel();
        fechaFinDC = new com.toedter.calendar.JDateChooser();
        fechaFinL = new javax.swing.JLabel();
        posicionesCB = new javax.swing.JComboBox<>();
        posicionesL = new javax.swing.JLabel();
        dorsalL = new javax.swing.JLabel();
        dorsalTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreL.setText("Nombre");

        descL.setText("Descripción");

        jScrollPane1.setViewportView(equiposJugadoresList);

        equiposL.setText("Equipos");

        guardarB.setText("Guardar");

        descartarB.setText("Descartar");
        descartarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarBActionPerformed(evt);
            }
        });

        salirB.setText("Salir");
        salirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBActionPerformed(evt);
            }
        });

        fechaIniL.setText("Fecha de Inicio");

        fechaFinL.setText("Fecha de Fin");

        posicionesL.setText("Posición");

        dorsalL.setText("Dorsal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaIniL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(equiposL))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaFinL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaFinDC, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(posicionesL)
                                    .addComponent(dorsalL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(posicionesCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dorsalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(descL)
                                    .addComponent(nombreL))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(descTF, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(nombreTF)))
                            .addComponent(fechaInicioDC, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salirB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descartarB)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreL)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descL)
                    .addComponent(descTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(posicionesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(posicionesL))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dorsalL)
                                .addComponent(dorsalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fechaIniL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fechaInicioDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14)
                                    .addComponent(fechaFinL))
                                .addComponent(equiposL))
                            .addGap(9, 9, 9)
                            .addComponent(fechaFinDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarB)
                    .addComponent(descartarB)
                    .addComponent(salirB))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBActionPerformed
        padre.setVisible(true);
		//TODO azd
    }//GEN-LAST:event_salirBActionPerformed

    private void descartarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descartarBActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CreacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CreacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CreacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CreacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CreacionGUI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descL;
    private javax.swing.JTextField descTF;
    private javax.swing.JButton descartarB;
    private javax.swing.JLabel dorsalL;
    private javax.swing.JTextField dorsalTF;
    private javax.swing.JList<String> equiposJugadoresList;
    private javax.swing.JLabel equiposL;
    private com.toedter.calendar.JDateChooser fechaFinDC;
    private javax.swing.JLabel fechaFinL;
    private javax.swing.JLabel fechaIniL;
    private com.toedter.calendar.JDateChooser fechaInicioDC;
    private javax.swing.JButton guardarB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreL;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JComboBox<String> posicionesCB;
    private javax.swing.JLabel posicionesL;
    private javax.swing.JButton salirB;
    // End of variables declaration//GEN-END:variables
}
